#cloud-config
package_update: true
package_upgrade: true

packages:
  - zsh
  - git
  - wget
  - unzip
  - screen
  - tmux
  - tree
  - vim
  - jq
  - util-linux-user
  - mariadb1011-server
  - java-21-amazon-corretto-devel

# Set the default user's shell to zsh.
# NOTE: The default user on Amazon Linux is 'ec2-user'
system_info:
  default_user:
    shell: /bin/zsh

runcmd:
  # Reinstall `curl`
  - sudo yum install --allowerasing -y curl
  # Remove Amazon Linux banner
  - sudo touch /etc/motd.d/30-banner
  # Install Oh My Zsh non-interactively for the 'ec2-user'
  # The `"" --unattended` part prevents the script from hanging.
  - su - ec2-user -c 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended'
  # Install Powerlevel10k theme
  - su - ec2-user -c "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
  # Install Zsh Syntax Highlighting plugin
  - su - ec2-user -c "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting"
  # Install Zsh Auto Suggestions plugin
  - su - ec2-user -c "git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
  # Edit `.zshrc` to set the theme and add the new plugins
  - su - ec2-user -c "sed -i 's/ZSH_THEME=\"robbyrussell\"/ZSH_THEME=\"powerlevel10k\/powerlevel10k\"/' ~/.zshrc"
  - su - ec2-user -c "sed -i '/plugins=(git)/c\plugins=(git zsh-autosuggestions zsh-syntax-highlighting)' ~/.zshrc"
